sonar.projectKey=pijonsauvaj_projet-genie-logiciel
sonar.organization=pijonsauvaj
sonar.java.binaries=target/classes
sonar.exclusions=src/main/java/fr/uparis/projet_genie_logiciel/App.java, \
                 src/test.java