sonar.projectKey=pijonsauvaj_projet-genie-logiciel
sonar.organization=pijonsauvaj
sonar.java.binaries=target/classes
sonar.coverage.exclusions=src/test/java/**
sonar.java.coveragePlugin=jacoco
sonar.jacoco.reportPaths=target/jacoco.exec
sonar.exclusions=\
  **/presentation/CLI
