name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
      - name: Build
        run: mvn compile -B
      - name: Run tests
        run: mvn test -B
              - name: SonarQube Cloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=pijonsauvaj_projet-genie-logiciel
            -Dsonar.organization=pijonsauvaj
            -Dsonar.java.binaries=target/classes
            -Dsonar.exclusions=src/main/java/fr/uparis/projet_genie_logiciel/App.java
            -Dsonar.test.exclusions=src/test/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          distribution: 'temurin'
          cache: maven
